/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Certificados;

import GUIPrincipal.Inicial;
import javax.swing.JOptionPane;

/**
 *
 * @author Qualidade
 */
public class Consultar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consultar
     */
    public Consultar() {
        initComponents();
    }

    private Certificado certificado;

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cnpj = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nNota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nPedido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        codProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        valorQnt = new javax.swing.JTextField();
        unidadeQnt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        complemento = new javax.swing.JTextField();
        complementoValor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensagem = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        nCertificado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        norma = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nCertOrig = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        composicao = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        caracteristica = new javax.swing.JTextArea();
        descricao = new javax.swing.JTextField();
        cliente = new javax.swing.JLabel();
        tratamento = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Consultar - Certificado");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Cadastro/icone2.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 8, -1, -1));
        getContentPane().add(cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 8, 300, 14));

        jLabel2.setText("Nº Nota:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 7, 106, -1));

        nNota.setEditable(false);
        getContentPane().add(nNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 117, -1));

        jLabel3.setText("Nº Pedido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 59, 107, -1));

        nPedido.setEditable(false);
        nPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(nPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 79, 107, -1));

        jLabel4.setText("Item:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 59, 122, -1));

        codProduto.setEditable(false);
        getContentPane().add(codProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 79, 122, -1));

        jLabel5.setText("Quantidade:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 57, 104, -1));

        valorQnt.setEditable(false);
        getContentPane().add(valorQnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 77, 94, -1));
        getContentPane().add(unidadeQnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 77, 32, 20));

        jLabel7.setText("Tratamento:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 110, 100, -1));

        jLabel8.setText("Complemento:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 114, -1, -1));

        complemento.setEditable(false);
        getContentPane().add(complemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 130, 200, -1));

        complementoValor.setEditable(false);
        getContentPane().add(complementoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 130, 176, -1));

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, -1));

        mensagem.setEditable(false);
        mensagem.setColumns(20);
        mensagem.setForeground(new java.awt.Color(204, 0, 0));
        mensagem.setRows(5);
        mensagem.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        jScrollPane1.setViewportView(mensagem);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 168, 394, 239));

        jLabel6.setText("Nº Certificado");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 7, -1, -1));
        getContentPane().add(nCertificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 100, -1));

        jLabel9.setText("Descrição:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 59, 253, -1));

        jLabel10.setText("Norma:");

        norma.setEditable(false);

        jLabel11.setText("Nº Cert. Origi:");

        nCertOrig.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(norma))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nCertOrig, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(norma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nCertOrig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Geral", jPanel1);

        composicao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Composição", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(composicao);

        jTabbedPane1.addTab("Quimica", jScrollPane2);

        caracteristica.setEditable(false);
        caracteristica.setColumns(20);
        caracteristica.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        caracteristica.setRows(5);
        jScrollPane3.setViewportView(caracteristica);

        jTabbedPane1.addTab("Fisica", jScrollPane3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 167, 260, 210));

        descricao.setEditable(false);
        getContentPane().add(descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 79, 253, -1));
        getContentPane().add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 360, 20));
        getContentPane().add(tratamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 120, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nPedidoActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        Inicial.principal.menuPrincipal.setVisible(true);
    }//GEN-LAST:event_formInternalFrameClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:]
        try {
            certificado = ConsultarCertificado.consultarCertificado(Integer.parseInt(nCertificado.getText()));
            atualizarCampos();
            atualizarMensagem();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "O Certificado tem que ser em numero inteiro.\nSem Pontos ou virgulas.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void atualizarCampos() {
        nNota.setText(Certificado.getNota());
        cliente.setText(Certificado.getCliente());
        cnpj.setText(Certificado.getCNPJ());
        codProduto.setText(Certificado.getProduto().getCodigo());
        descricao.setText(Certificado.getProduto().getDescricao());
        tratamento.setText(Certificado.getTratamento());
        valorQnt.setText(Certificado.getQnt().split(" ")[0]);
        unidadeQnt.setText(Certificado.getQnt().split(" ")[1]);
        complemento.setText(Certificado.getComplemento());
        complementoValor.setText(Certificado.getComplementoDescricao());
        nPedido.setText(Certificado.getPedido());
        norma.setText(Certificado.getProduto().getNorma());
        nCertOrig.setText(Certificado.getProduto().getCertificado());

        composicao.setValueAt(Certificado.getProduto().getQ1(), 0, 0);
        composicao.setValueAt(Certificado.getProduto().getV1(), 0, 1);
        composicao.setValueAt(Certificado.getProduto().getQ2(), 1, 0);
        composicao.setValueAt(Certificado.getProduto().getV2(), 1, 1);
        composicao.setValueAt(Certificado.getProduto().getQ3(), 2, 0);
        composicao.setValueAt(Certificado.getProduto().getV3(), 2, 1);
        composicao.setValueAt(Certificado.getProduto().getQ4(), 3, 0);
        composicao.setValueAt(Certificado.getProduto().getV4(), 3, 1);
        composicao.setValueAt(Certificado.getProduto().getQ5(), 4, 0);
        composicao.setValueAt(Certificado.getProduto().getV5(), 4, 1);
        composicao.setValueAt(Certificado.getProduto().getQ6(), 5, 0);
        composicao.setValueAt(Certificado.getProduto().getV6(), 5, 1);
        composicao.setValueAt(Certificado.getProduto().getQ7(), 6, 0);
        composicao.setValueAt(Certificado.getProduto().getV7(), 6, 1);
        composicao.setValueAt(Certificado.getProduto().getQ8(), 7, 0);
        composicao.setValueAt(Certificado.getProduto().getV8(), 7, 1);
        composicao.setValueAt(Certificado.getProduto().getQ9(), 8, 0);
        composicao.setValueAt(Certificado.getProduto().getV9(), 8, 1);
        composicao.setValueAt(Certificado.getProduto().getQ10(), 9, 0);
        composicao.setValueAt(Certificado.getProduto().getV10(), 9, 1);
        composicao.setValueAt(Certificado.getProduto().getQ11(), 10, 0);
        composicao.setValueAt(Certificado.getProduto().getV11(), 10, 1);
        composicao.setValueAt(Certificado.getProduto().getQ12(), 11, 0);
        composicao.setValueAt(Certificado.getProduto().getV12(), 11, 1);
        composicao.setValueAt(Certificado.getProduto().getQ13(), 12, 0);
        composicao.setValueAt(Certificado.getProduto().getV13(), 12, 1);
        composicao.setValueAt(Certificado.getProduto().getQ14(), 13, 0);
        composicao.setValueAt(Certificado.getProduto().getV14(), 13, 1);
        
        caracteristica.setText(Certificado.getProduto().getCaracteristica());
    }

    private void atualizarMensagem(){
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea caracteristica;
    private javax.swing.JLabel cliente;
    private javax.swing.JLabel cnpj;
    private javax.swing.JTextField codProduto;
    private javax.swing.JTextField complemento;
    private javax.swing.JTextField complementoValor;
    private javax.swing.JTable composicao;
    private javax.swing.JTextField descricao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea mensagem;
    private javax.swing.JTextField nCertOrig;
    private javax.swing.JTextField nCertificado;
    private javax.swing.JTextField nNota;
    private javax.swing.JTextField nPedido;
    private javax.swing.JTextField norma;
    private javax.swing.JLabel tratamento;
    private javax.swing.JLabel unidadeQnt;
    private javax.swing.JTextField valorQnt;
    // End of variables declaration//GEN-END:variables
}
